

try:
    print(i)

except NameError as e:
    print(e)
